### PR TITLE
csharp bitmex api project updates and compile error fixes

### PR DESCRIPTION
**Pull request by wildbunny**
I've added proper request authentication and signature generation compatible with bitmex api.  Added proper rate limiting using a semaphore for both synchronous and async methods. Fixed a bunch of compile errors. Also now using correct datetime utc serialisation. Added a simple demo project which demonstrates the ability of this to connect to a private bitmex api endpoint and render the deposit address and list of open positions.

### CODE REVIEW

**Comment by STRML** [comment]
Thanks a bunch for this. Just wanted to give you some background on where we're taking these connectors:

* If the tests are wrong (`IsInstanceOf`), that would be something we should take up with [swagger-codegen](https://github.com/swagger-api/swagger-codegen/).
* We're going to be deprecating the `api-key` scheme in favor of an `api-token` that is a simple shared secret. There is no practical reason for creating such a complex scheme over modern TLS. Once that is in place, we'll update the swagger docs and these adapters should work out of the box.

**Comment by STRML** [comment]
Hi @wildbunny,

Could you refactor this into the `/official-http/` directory? Anything in the `/clients/` directory will be automatically destroyed the next time we run swagger-codegen.

**Comment by kirsan31** [comment]
@STRML 
> We're going to be deprecating the api-key scheme in favor of an api-token that is a simple shared secret. There is no practical reason for creating such a complex scheme over modern TLS. Once that is in place, we'll update the swagger docs and these adapters should work out of the box.

Any timeline on this?

**Comment by STRML** [comment]
Unfortunately this work is still in progress, as system scaling and other security features have taken ultimate precedence. We still have this in mind, as we want these auto-generated connectors to work out of the box without any special attention being paid toward auth.

Will close this for now.

**Pull request closed without merging**
