### PR TITLE
Fix bug #203

### PR DESCRIPTION
**Pull request by smalljiny**
Change init value for reduce function like v0.3.0.

### CODE REVIEW

**Comment by andersea** [comment]
I made this piece of code. I have read the bug report and this pull request. I am afraid I do not see what the problem is.

Can you explain step by step what goes wrong and why/how this patch fixes the problem.

**Comment by andersea** [comment]
Studying this some more, it looks to me like this will reintroduce the bug from #120. I am not comfortable recommending this patch unless we can be sure it doesn't cause further breakage.

**Comment by STRML** [comment]
We merged this, but it's actually not the correct fix. Working on a more correct one shortly.

**Comment by andersea** [comment]
Good luck. :)

**Pull request closed without merging**
